# mkdocs-library configuration variables' default values.
# These can be overridden in a project's
# _mkdocs-library-config/config.yml file

# Name of a book considered the parent book
# If this is empty ('' or false) or if no book with that
# name is found in the docs directory the project does
# not have a parenty book but consists of siblings only.
library_book: 'main'

# If no outline.yml file is given then the list of
# books is read from the books subdirectory. If this
# includes a book whose name matches the library_book
# option it will be created as a parent book.
# By default it will be placed at the start of the book
# list, but this can be overridden with this option.
library_book_at_start: true

# Text to be used for the "home" link to the parent book.
# If this is set to an empty string in the project configuration
# the book's actual title is used instead.
library_link_text: 'Main Book'

# Add navigation links to other books in a project
# (if the 'tabs' feature of the Material theme is used
# these are added to each secondary level navigation.)
# By default this should be active, set it to false if
# the project has other means of linking to the sibling
# books (e.g. a dedicated page, or if only the parent
# book wants to link to the children).
# Can be overridden on project and book level.
link_to_siblings: true

# Position of the sibling links [start|end]
siblings_position: 'end'

# Title of the group containing the sibling links
siblings_link_title: 'Sibling Books'

# Path to the generated project site.
# If this is a relative path it is considered
# relative to the project's root directory.
site_root: 'site'

# Name of a given book, should be specified in each book's
# config file. Will be rendered to mkdocs.yml as 'site_name'
book_name: 'NO BOOK NAME'

# Name of a script to be used after building a project
# (must be executable and work without arguments,
# however, command line interaction (e.g. passwords) is possible.)
deploy_script: 'deploy'

# When no recipe is chosen through the command line option
# the default is the full build sequence.
default_recipe: 'build'
