#!/usr/bin/env python3

# This file is part of the merge-mkdocs project,
# https://github.com/uliska/merge-mkdocs
# https://glarean.mh-freiburg.de/git/GLAREAN-Doku/merge-mkdocs/
#
# Copyright (c) 2020 by Urs Liska
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
# See http://www.gnu.org/licenses/ for more information.

"""
Representation of a merge-mkdocs project
"""

import os
import sys

from subprocess import Popen

from book import MainBook, SubBook
from util import read_yaml, missing_file


MKDOCS_HEADER_COMMENT = """
### This book configuration file is generated by merge-mkdocs
### Do not edit this file.
### Please refer to the documentation for details

"""


class Project(object):
    """A merge-mkdocs project, represents a directory structure.
    """

    def __init__(self, cl_args):

        # Project root directory, defaulting to current working directory
        self._root = cl_args.root
        # List of books. If present, the main book is the first in this list.
        self._books = []
        self._has_main_book = False

        # Program and project site configuration files
        config_dir = os.path.join(self._root, '_merge-mkdocs-config')
        self._config_file = os.path.join(config_dir, 'config.yml')
        self._template_file = template_file = os.path.join(
            config_dir, 'template.yml'
        )
        self._defaults_file = defaults_file = os.path.join(
            config_dir, 'defaults.yml'
        )
        self._outline_file = outline_file = os.path.join(
            config_dir, 'outline.yml'
        )

    # TODO: Improve
    # (https://github.com/uliska/merge-mkdocs/issues/2)
        if not (
            os.path.exists(template_file)
            and os.path.exists(defaults_file)
            and os.path.exists(outline_file)
        ):
            raise Exception("Project, Defaults, or Books file missing")

        # Read and parse the different configuration files
        self._config = self.read_config()
        self._defaults = read_yaml(defaults_file)
        self._template = self.read_template()
        self._books = self.load_books()

        # Decide which recipe is going to be executed
        self._recipe = cl_args.recipe or self.config('default_recipe')

    def book_nav(self, target):
        """
        Returns a string list with the navigation entry
        pointing to the given non-home book.
        """
        return [
            '  - "{}":'.format(target.title()),
            '    - Home: "../{}/index.html"'.format(target.name())
        ]

    def books(self):
        """
        Returns a list with all book objects.
        If the project has a main book it will be the first element.
        """
        return self._books

    def config(self, key=None):
        """
        Returns a given configuration value,
        or the whole config dictionary.
        """
        if key:
            return self._config[key]
        else:
            return self._config

    def config_file(self):
        return self._config_file

    def defaults(self, key=None):
        if key:
            return self._defaults[key]
        else:
            return self._defaults

    def exec_recipe(self):
        """Execute a given recipe, i.e. sequence of tasks."""
        recipes = {
            'merge-sources': [
                'task_merge_sources'
            ],
            'build': [
                'task_merge_sources',
                'task_build_site',
                'task_merge_indexes'
            ],
            'merge-indexes': [
                'task_merge_indexes'
            ],
            'deploy': [
                'task_deploy'
            ],
            'all': [
                'task_build_site',
                'task_deploy'
            ]
        }
        recipe = recipes[self.recipe()]
        for step in recipe:
            getattr(self, step)()

    def home_nav(self):
        """
        Returns a navigation entry to the main book if one exists
        in the project, otherwise an empty (string) list.
        """
        result = []
        main = self.main_book()
        if main:
            result.append('  - "{}":'.format(main.title()))
            result.append('    - Home: ../index.html'.format(main.name()))
        return result

    def load_books(self):
        """Create the book objects."""
    # TODO:
    # https://github.com/uliska/merge-mkdocs/issues/1
        result = []
        outline = read_yaml(self.outline_file())
        main = outline.get('main', None)
        if main:
            self._has_main_book = True
            result.append(MainBook(self, main))
        for name, title in outline['books'].items():
            # The subbook entries are done different from the main book,
            # so we have to explicitly create the dict here
            result.append(SubBook(self, {
                'name': name,
                'title': title
            }))
        return result

    def main_book(self):
        """Return the MainBook object, or None."""
        if self._has_main_book:
            return self.books()[0]
        else:
            return None

    def outline_file(self):
        """The file where the book outline is configured, if present."""
        return self._outline_file

    def read_config(self):
        """Read the project's configuration file.
        Provides default values if not provided by project configuration.
        """
        defaults = {
            'link_to_siblings': False,
            'deploy_script': 'deploy',
            'site_root': 'site',
            'default_recipe': 'build'
        }
        config = read_yaml(self.config_file())
        config_file = os.path.join(
            self.root(),
            '_merge_mkdocs-config',
            'config.yml'
        )

        result = {}
        for key in defaults:
            result[key] = config.get(key, defaults[key])

        return result

    def read_template(self):
        """Read the template file."""

    # TODO: Validate against defaults
    # (https://github.com/uliska/merge-mkdocs/issues/2)
        with open(self.template_file(), 'r') as f:
            return MKDOCS_HEADER_COMMENT + f.read()

    def recipe(self):
        """The recipe to be performed.
        This can be configured at various levels:
        - value to the command line argument --recipe
          this always takes precedence
        - default_recipe in config.yml
          if this is given it will be used if no --recipe arg is present
        - built-in default_recipe
          lacking *any* user configuration the 'build' recipe is executed
        """
        return self._recipe

    def root(self):
        """The project's root directory.
        Either given on the command line or the current working directory.
        """
        return self._root

    def site_root(self):
        """
        The relative path to the generated site's root.
        Defaults to 'site'.
        """
        return self.config('site_root')

    #################################################
    # High-level implementation of the various tasks.

    def task_build_site(self):
        """Build the site
        Start with the main book because this clears the total site.
        """
        for book in self.books():
            book.build()

    def task_deploy(self):
        """Deploy the site using a user/project-provided script.
        The script can be given as a configuration option, or
        it defaults to 'deploy'. It may be given as relative to
        the project root or as an absolute path.
        The script has to be executable, and it has to work without
        user interaction.
        """
        print("Deploying site")
        script = self.config('deploy_script')
        if not os.path.isabs(script):
            script = os.path.join(self.root(), script)
        p = Popen([script], shell=True)
        p.wait()
        output, errors = p.communicate()
        print(output)
        if errors:
            raise Exception(errors)
        print("\n=======\n")

    def task_merge_indexes(self):
        """Merge search indexes
        MkDocs produces a search index in a JSON file, pointing to
        all documents with links relative to the site's root directory.
        This task enhances these indexes by the indexes of all other books.
        """
        books = self.books()
        # The index objects are initially created in this list comprehension
        indexes = [book.search_index() for book in books]
        for i in indexes:
            # Merge in updated indexes to the other books
            i.update(books)
            # Update JSON file
            i.write()

    def task_merge_sources(self):
        """Preprocess the sources.
        Process templates and navigation files
        for each book.
        """
        for book in self.books():
            # fill in values for template fields
            book.update_template()
            # Generate local navigation and
            # add links to other book parts
            self.update_nav(book)
            # write the book's mkdocs.yml file
            book.write_yaml()

    # High-level implementation of the various tasks.
    #################################################

    def template(self):
        """The template for a mkdocs.yml file.
        This is basically a mkdocs.yml file wtihout the nav: element
        where <<<name>>> template fields can be replaced with values
        from defaults or a book-config.yml file.
        """
        return self._template

    def template_file(self):
        """The project's template file."""
        return self._template_file

    def update_nav(self, book):
        """Process a book's navigation structure.
        Integrate the local navigation in the multi-book set-up.
        """
    # TODO: Enhance
    # (https://github.com/uliska/merge-mkdocs/issues/1)
        result = ['nav:']
        # Subbooks get a main link to the main book
        if not book.is_main_book():
            result.extend(self.home_nav())
        # By default sibling books are *not* linked to
        # because that is somewhat redundant.
        # The default is having the whole navigation structure
        # under control of the subbook and just add the link
        # the the main book.
        if self.config('link_to_siblings'):
            for b in self.books():
                if b != self.main_book():
                    # exclude main book because we already have it
                    result.extend(self.book_nav(b))
                if b == book:
                    # the *current* book
                    # - remove the "home" line
                    # - and append the local navigation
                    result.pop()
                    for line in book.nav():
                        result.append('    {}'.format(line))#
        else:
            # Simply add the local navigation.
            for line in book.nav():
                result.append('  {}'.format(line))
        book.set_nav(result)
